/* Fixup */
SYSCALL_ARGC(LKL__NR_lookup_dcookie, 3)
SYSCALL_ARGC(LKL__NR_vhangup, 0)
SYSCALL_ARGC(LKL__NR_sync, 0)
SYSCALL_ARGC(LKL__NR_sched_yield, 0)
SYSCALL_ARGC(LKL__NR_restart_syscall, 0)
SYSCALL_ARGC(LKL__NR_setsid, 0)
SYSCALL_ARGC(LKL__NR_getpid, 0)
SYSCALL_ARGC(LKL__NR_getppid, 0)
SYSCALL_ARGC(LKL__NR_getuid, 0)
SYSCALL_ARGC(LKL__NR_geteuid, 0)
SYSCALL_ARGC(LKL__NR_getgid, 0)
SYSCALL_ARGC(LKL__NR_getegid, 0)
SYSCALL_ARGC(LKL__NR_gettid, 0)
