#define LKL__NR_io_setup 0
#define LKL__NR_io_destroy 1
#define LKL__NR_io_submit 2
#define LKL__NR_io_cancel 3
#define LKL__NR_io_getevents 4
#define LKL__NR_setxattr 5
#define LKL__NR_lsetxattr 6
#define LKL__NR_fsetxattr 7
#define LKL__NR_getxattr 8
#define LKL__NR_lgetxattr 9
#define LKL__NR_fgetxattr 10
#define LKL__NR_listxattr 11
#define LKL__NR_llistxattr 12
#define LKL__NR_flistxattr 13
#define LKL__NR_removexattr 14
#define LKL__NR_lremovexattr 15
#define LKL__NR_fremovexattr 16
#define LKL__NR_getcwd 17
#define LKL__NR_lookup_dcookie 18
#define LKL__NR_eventfd2 19
#define LKL__NR_epoll_create1 20
#define LKL__NR_epoll_ctl 21
#define LKL__NR_epoll_pwait 22
#define LKL__NR_dup 23
#define LKL__NR_dup3 24
#define LKL__NR3264_fcntl 25
#define LKL__NR_inotify_init1 26
#define LKL__NR_inotify_add_watch 27
#define LKL__NR_inotify_rm_watch 28
#define LKL__NR_ioctl 29
#define LKL__NR_ioprio_set 30
#define LKL__NR_ioprio_get 31
#define LKL__NR_flock 32
#define LKL__NR_mknodat 33
#define LKL__NR_mkdirat 34
#define LKL__NR_unlinkat 35
#define LKL__NR_symlinkat 36
#define LKL__NR_linkat 37
#define LKL__NR_renameat 38
#define LKL__NR_umount2 39
#define LKL__NR_mount 40
#define LKL__NR_pivot_root 41
#define LKL__NR_nfsservctl 42
#define LKL__NR3264_statfs 43
#define LKL__NR3264_fstatfs 44
#define LKL__NR3264_truncate 45
#define LKL__NR3264_ftruncate 46
#define LKL__NR_fallocate 47
#define LKL__NR_faccessat 48
#define LKL__NR_chdir 49
#define LKL__NR_fchdir 50
#define LKL__NR_chroot 51
#define LKL__NR_fchmod 52
#define LKL__NR_fchmodat 53
#define LKL__NR_fchownat 54
#define LKL__NR_fchown 55
#define LKL__NR_openat 56
#define LKL__NR_close 57
#define LKL__NR_vhangup 58
#define LKL__NR_pipe2 59
#define LKL__NR_quotactl 60
#define LKL__NR_getdents64 61
#define LKL__NR3264_lseek 62
#define LKL__NR_read 63
#define LKL__NR_write 64
#define LKL__NR_readv 65
#define LKL__NR_writev 66
#define LKL__NR_pread64 67
#define LKL__NR_pwrite64 68
#define LKL__NR_preadv 69
#define LKL__NR_pwritev 70
#define LKL__NR3264_sendfile 71
#define LKL__NR_signalfd4 74
#define LKL__NR_vmsplice 75
#define LKL__NR_splice 76
#define LKL__NR_tee 77
#define LKL__NR_readlinkat 78
#define LKL__NR3264_fstatat 79
#define LKL__NR3264_fstat 80
#define LKL__NR_sync 81
#define LKL__NR_fsync 82
#define LKL__NR_fdatasync 83
#define LKL__NR_sync_file_range2 84
#define LKL__NR_sync_file_range 84
#define LKL__NR_timerfd_create 85
#define LKL__NR_acct 89
#define LKL__NR_capget 90
#define LKL__NR_capset 91
#define LKL__NR_personality 92
#define LKL__NR_exit 93
#define LKL__NR_exit_group 94
#define LKL__NR_waitid 95
#define LKL__NR_set_tid_address 96
#define LKL__NR_unshare 97
#define LKL__NR_set_robust_list 99
#define LKL__NR_get_robust_list 100
#define LKL__NR_nanosleep 101
#define LKL__NR_getitimer 102
#define LKL__NR_setitimer 103
#define LKL__NR_kexec_load 104
#define LKL__NR_init_module 105
#define LKL__NR_delete_module 106
#define LKL__NR_timer_create 107
#define LKL__NR_timer_gettime 108
#define LKL__NR_timer_getoverrun 109
#define LKL__NR_timer_settime 110
#define LKL__NR_timer_delete 111
#define LKL__NR_syslog 116
#define LKL__NR_ptrace 117
#define LKL__NR_sched_setparam 118
#define LKL__NR_sched_setscheduler 119
#define LKL__NR_sched_getscheduler 120
#define LKL__NR_sched_getparam 121
#define LKL__NR_sched_setaffinity 122
#define LKL__NR_sched_getaffinity 123
#define LKL__NR_sched_yield 124
#define LKL__NR_sched_get_priority_max 125
#define LKL__NR_sched_get_priority_min 126
#define LKL__NR_restart_syscall 128
#define LKL__NR_kill 129
#define LKL__NR_tkill 130
#define LKL__NR_tgkill 131
#define LKL__NR_sigaltstack 132
#define LKL__NR_rt_sigsuspend 133
#define LKL__NR_rt_sigaction 134
#define LKL__NR_rt_sigprocmask 135
#define LKL__NR_rt_sigpending 136
#define LKL__NR_rt_sigqueueinfo 138
#define LKL__NR_rt_sigreturn 139
#define LKL__NR_setpriority 140
#define LKL__NR_getpriority 141
#define LKL__NR_reboot 142
#define LKL__NR_setregid 143
#define LKL__NR_setgid 144
#define LKL__NR_setreuid 145
#define LKL__NR_setuid 146
#define LKL__NR_setresuid 147
#define LKL__NR_getresuid 148
#define LKL__NR_setresgid 149
#define LKL__NR_getresgid 150
#define LKL__NR_setfsuid 151
#define LKL__NR_setfsgid 152
#define LKL__NR_times 153
#define LKL__NR_setpgid 154
#define LKL__NR_getpgid 155
#define LKL__NR_getsid 156
#define LKL__NR_setsid 157
#define LKL__NR_getgroups 158
#define LKL__NR_setgroups 159
#define LKL__NR_uname 160
#define LKL__NR_sethostname 161
#define LKL__NR_setdomainname 162
#define LKL__NR_getrlimit 163
#define LKL__NR_setrlimit 164
#define LKL__NR_getrusage 165
#define LKL__NR_umask 166
#define LKL__NR_prctl 167
#define LKL__NR_getcpu 168
#define LKL__NR_gettimeofday 169
#define LKL__NR_settimeofday 170
#define LKL__NR_adjtimex 171
#define LKL__NR_getpid 172
#define LKL__NR_getppid 173
#define LKL__NR_getuid 174
#define LKL__NR_geteuid 175
#define LKL__NR_getgid 176
#define LKL__NR_getegid 177
#define LKL__NR_gettid 178
#define LKL__NR_sysinfo 179
#define LKL__NR_mq_open 180
#define LKL__NR_mq_unlink 181
#define LKL__NR_mq_notify 184
#define LKL__NR_mq_getsetattr 185
#define LKL__NR_msgget 186
#define LKL__NR_msgctl 187
#define LKL__NR_msgrcv 188
#define LKL__NR_msgsnd 189
#define LKL__NR_semget 190
#define LKL__NR_semctl 191
#define LKL__NR_semop 193
#define LKL__NR_shmget 194
#define LKL__NR_shmctl 195
#define LKL__NR_shmat 196
#define LKL__NR_shmdt 197
#define LKL__NR_socket 198
#define LKL__NR_socketpair 199
#define LKL__NR_bind 200
#define LKL__NR_listen 201
#define LKL__NR_accept 202
#define LKL__NR_connect 203
#define LKL__NR_getsockname 204
#define LKL__NR_getpeername 205
#define LKL__NR_sendto 206
#define LKL__NR_recvfrom 207
#define LKL__NR_setsockopt 208
#define LKL__NR_getsockopt 209
#define LKL__NR_shutdown 210
#define LKL__NR_sendmsg 211
#define LKL__NR_recvmsg 212
#define LKL__NR_readahead 213
#define LKL__NR_brk 214
#define LKL__NR_munmap 215
#define LKL__NR_mremap 216
#define LKL__NR_add_key 217
#define LKL__NR_request_key 218
#define LKL__NR_keyctl 219
#define LKL__NR_clone 220
#define LKL__NR_execve 221
#define LKL__NR3264_mmap 222
#define LKL__NR3264_fadvise64 223
#define LKL__NR_swapon 224
#define LKL__NR_swapoff 225
#define LKL__NR_mprotect 226
#define LKL__NR_msync 227
#define LKL__NR_mlock 228
#define LKL__NR_munlock 229
#define LKL__NR_mlockall 230
#define LKL__NR_munlockall 231
#define LKL__NR_mincore 232
#define LKL__NR_madvise 233
#define LKL__NR_remap_file_pages 234
#define LKL__NR_mbind 235
#define LKL__NR_get_mempolicy 236
#define LKL__NR_set_mempolicy 237
#define LKL__NR_migrate_pages 238
#define LKL__NR_move_pages 239
#define LKL__NR_rt_tgsigqueueinfo 240
#define LKL__NR_perf_event_open 241
#define LKL__NR_accept4 242
#define LKL__NR_arch_specific_syscall 244
#define LKL__NR_wait4 260
#define LKL__NR_prlimit64 261
#define LKL__NR_fanotify_init 262
#define LKL__NR_fanotify_mark 263
#define LKL__NR_name_to_handle_at         264
#define LKL__NR_open_by_handle_at         265
#define LKL__NR_syncfs 267
#define LKL__NR_setns 268
#define LKL__NR_sendmmsg 269
#define LKL__NR_process_vm_readv 270
#define LKL__NR_process_vm_writev 271
#define LKL__NR_kcmp 272
#define LKL__NR_finit_module 273
#define LKL__NR_sched_setattr 274
#define LKL__NR_sched_getattr 275
#define LKL__NR_renameat2 276
#define LKL__NR_seccomp 277
#define LKL__NR_getrandom 278
#define LKL__NR_memfd_create 279
#define LKL__NR_bpf 280
#define LKL__NR_execveat 281
#define LKL__NR_userfaultfd 282
#define LKL__NR_membarrier 283
#define LKL__NR_mlock2 284
#define LKL__NR_copy_file_range 285
#define LKL__NR_preadv2 286
#define LKL__NR_pwritev2 287
#define LKL__NR_pkey_mprotect 288
#define LKL__NR_pkey_alloc 289
#define LKL__NR_pkey_free 290
#define LKL__NR_statx 291
#define LKL__NR_rseq 293
#define LKL__NR_kexec_file_load 294
#define LKL__NR_clock_gettime64 403
#define LKL__NR_clock_settime64 404
#define LKL__NR_clock_adjtime64 405
#define LKL__NR_clock_getres_time64 406
#define LKL__NR_clock_nanosleep_time64 407
#define LKL__NR_timer_gettime64 408
#define LKL__NR_timer_settime64 409
#define LKL__NR_timerfd_gettime64 410
#define LKL__NR_timerfd_settime64 411
#define LKL__NR_utimensat_time64 412
#define LKL__NR_pselect6_time64 413
#define LKL__NR_ppoll_time64 414
#define LKL__NR_io_pgetevents_time64 416
#define LKL__NR_recvmmsg_time64 417
#define LKL__NR_mq_timedsend_time64 418
#define LKL__NR_mq_timedreceive_time64 419
#define LKL__NR_semtimedop_time64 420
#define LKL__NR_rt_sigtimedwait_time64 421
#define LKL__NR_futex_time64 422
#define LKL__NR_sched_rr_get_interval_time64 423
#define LKL__NR_pidfd_send_signal 424
#define LKL__NR_io_uring_setup 425
#define LKL__NR_io_uring_enter 426
#define LKL__NR_io_uring_register 427
#define LKL__NR_open_tree 428
#define LKL__NR_move_mount 429
#define LKL__NR_fsopen 430
#define LKL__NR_fsconfig 431
#define LKL__NR_fsmount 432
#define LKL__NR_fspick 433
#define LKL__NR_pidfd_open 434
#define LKL__NR_clone3 435
#define LKL__NR_close_range 436
#define LKL__NR_openat2 437
#define LKL__NR_pidfd_getfd 438
#define LKL__NR_faccessat2 439
#define LKL__NR_process_madvise 440
#define LKL__NR_epoll_pwait2 441
#define LKL__NR_mount_setattr 442
#define LKL__NR_quotactl_fd 443
#define LKL__NR_landlock_create_ruleset 444
#define LKL__NR_landlock_add_rule 445
#define LKL__NR_landlock_restrict_self 446
#define LKL__NR_memfd_secret 447
#define LKL__NR_process_mrelease 448
#define LKL__NR_futex_waitv 449
#define LKL__NR_set_mempolicy_home_node 450

#define LKL__NR_fcntl LKL__NR3264_fcntl
#define LKL__NR_statfs LKL__NR3264_statfs
#define LKL__NR_fstatfs LKL__NR3264_fstatfs
#define LKL__NR_truncate LKL__NR3264_truncate
#define LKL__NR_ftruncate LKL__NR3264_ftruncate
#define LKL__NR_lseek LKL__NR3264_lseek
#define LKL__NR_sendfile LKL__NR3264_sendfile
#define LKL__NR_newfstatat LKL__NR3264_fstatat
#define LKL__NR_fstat LKL__NR3264_fstat
#define LKL__NR_mmap LKL__NR3264_mmap
#define LKL__NR_fadvise64 LKL__NR3264_fadvise64
